from bot import CMD_INDEX


class _BotCommands:
    def __init__(self):
        self.StartCommand = f'start'
        self.MirrorCommand = f'mirror1'
        self.UnzipMirrorCommand = f'unzipmirror1'
        self.ZipMirrorCommand = f'zipmirror1'
        self.CancelMirror = f'cancel{CMD_INDEX}'
        self.CancelAllCommand = f'cancelall{CMD_INDEX}'
        self.ListCommand = f'list'
        self.SearchCommand = f'search{CMD_INDEX}'
        self.StatusCommand = f'status'
        self.AuthorizedUsersCommand = f'users'
        self.AuthorizeCommand = f'authorize'
        self.UnAuthorizeCommand = f'unauthorize'
        self.AddSudoCommand = f'addsudo'
        self.RmSudoCommand = f'rmsudo'
        self.PingCommand = f'ping'
        self.RestartCommand = f'restart{CMD_INDEX}'
        self.StatsCommand = f'stats'
        self.HelpCommand = f'help{CMD_INDEX}'
        self.LogCommand = f'log{CMD_INDEX}'
        self.CloneCommand = f'clone1'
        self.CountCommand = f'count{CMD_INDEX}'
        self.WatchCommand = f'watch1'
        self.ZipWatchCommand = f'zipwatch1'
        self.QbMirrorCommand = f'qbmirror1'
        self.QbUnzipMirrorCommand = f'qbunzipmirror1'
        self.QbZipMirrorCommand = f'qbzipmirror1'
        self.DeleteCommand = f'del{CMD_INDEX}'
        self.ShellCommand = f'shell1'
        self.ExecHelpCommand = f'exechelp{CMD_INDEX}'
        self.LeechSetCommand = f'leechset{CMD_INDEX}'
        self.SetThumbCommand = f'setthumb{CMD_INDEX}'
        self.LeechCommand = f'leech{CMD_INDEX}'
        self.UnzipLeechCommand = f'unzipleech{CMD_INDEX}'
        self.ZipLeechCommand = f'zipleech{CMD_INDEX}'
        self.QbLeechCommand = f'qbleech{CMD_INDEX}'
        self.QbUnzipLeechCommand = f'qbunzipleech{CMD_INDEX}'
        self.QbZipLeechCommand = f'qbzipleech{CMD_INDEX}'
        self.LeechWatchCommand = f'leechwatch{CMD_INDEX}'
        self.LeechZipWatchCommand = f'leechzipwatch{CMD_INDEX}'
        self.RssListCommand = f'rsslist1'
        self.RssGetCommand = f'rssget1'
        self.RssSubCommand = f'rsssub1'
        self.RssUnSubCommand = f'rssunsub1'
        self.RssSettingsCommand = f'rssset1'
        self.EvalCommand = f'eval{CMD_INDEX}'
        self.ExecCommand = f'exec{CMD_INDEX}'
        self.ClearLocalsCommand = f'clearlocals{CMD_INDEX}'

BotCommands = _BotCommands()
